[package]
name = "rust_os"
version = "0.1.0"
authors = ["Daniel Guddemi <danguddemi@gmail.com>"]
edition = "2018"

// panic on abort to disable stack unwinding (an OS specific task)

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
